apiVersion: apps/v1
kind: Deployment
metadata:
  name: queueoke
  labels:
    app: queueoke
spec:
  selector:
    matchLabels:
      app: queueoke
  template:
    metadata:
      labels:
        app: queueoke
    spec:
      containers:
      - name: queueoke
        image: IMAGE_NAME
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
            - name: DP_ENDPOINT
              value: "${DP_ENDPOINT}"
            - name: QUEUE_ID
              value: "${QUEUE_ID}"
            
              
      imagePullSecrets:
      - name: queueoke-secret #check secret.yaml
        